Create patch set 3
Change has been successfully rebased and submitted as 227b613248b03cf17533e565717cc89cd477fb23

1 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: test/utils/regen-test-files
Insertions: 1, Deletions: 5.

@@ -286,11 +286,7 @@
   # usually `arttestd` or `arttest)`, but the ART run-test TradeFed test runner
   # (`com.android.tradefed.testtype.ArtRunTest`) does not implement this yet.
   "826-infinite-loop",
-  # 832-cha-recursive: Fails with:
-  #
-  #   Test command execution failed with status FAILED: CommandResult: exit code=1, out=, err=Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
-  #           at Main.main(Main.java:21)
-  #
+  # 832-cha-recursive: Dependency on `libarttest`.
   "832-cha-recursive",
   "900-hello-plugin",
   "901-hello-ti-agent",
```


Patch-set: 3
Patch-set-description: Rebase
Subject: Exclude `art-run-test-832-cha-recursive` from automated executions.
Status: merged
Commit: 227b613248b03cf17533e565717cc89cd477fb23
Tag: autogenerated:gerrit:merged
Groups: 53c22fe59583cea48af6d7f506079907be7f007f
Label: Verified=+1
Label: Code-Review=+2 Gerrit User 1373864 <1373864@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=+2 Gerrit User 1884045 <1884045@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Open-Source-Licensing=+1 Gerrit User 1757831 <1757831@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Lint=+1 Gerrit User 1757831 <1757831@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0 Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Verified=+2 Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Verified-Together=+1 Gerrit User 1062513 <1062513@85c56323-6fa9-3386-8a01-6480fb634889>
Label: SUBM=+1
Submission-id: 1873779
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~PrologRule
Submitted-with: MAY: Build-Cop-Override
Submitted-with: MAY: Presubmit-Verified-Together
Submitted-with: MAY: Bypass-Presubmit
Submitted-with: MAY: Presubmit-Ready
Submitted-with: MAY: Autosubmit
Submitted-with: MAY: Exempt
Submitted-with: MAY: Global-Approval
Submitted-with: OK: Code-Review: Gerrit User 1884045 <1884045@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: MAY: Verified
Submitted-with: MAY: Open-Source-Licensing
Submitted-with: MAY: Lint
Submitted-with: MAY: Presubmit-Verified
Submitted-with: OK: Second-Party-Review: Gerrit User 1884045 <1884045@85c56323-6fa9-3386-8a01-6480fb634889>
Submitted-with: OK
Submitted-with: Rule-Name: code-owners~CodeOwnerSubmitRule