Update patch set 1
Patch Set 1:

There's no crashes, it runs to finish and just has empty output.cfg .


iam@invoker:/mnt/ssd3/workspace/aosp_master$ art/test/run-test --dev --host --optimizing 639-checker-code-sinking-classloaders
/mnt/ssd3/workspace/aosp_master/art/test/639-checker-code-sinking-classloaders: building...
  adding: classes.dex (deflated 44%)
  adding: classes.dex (deflated 46%)
build exit status: 0
/mnt/ssd3/workspace/aosp_master/art/test/639-checker-code-sinking-classloaders: running...
mkdir -p  /tmp/iam/test-126444/dalvik-cache/x86 /tmp/iam/test-126444/oat/x86 && true && timeout -k 1m -s SIGRTMIN+2 90s /mnt/ssd3/workspace/aosp_master/out/host/linux-x86/bin/dex2oatd --compiler-backend=Optimizing --dump-cfg=/tmp/iam/test-126444/graph.cfg -j1 --runtime-arg -Xnorelocate --boot-image=/mnt/ssd3/workspace/aosp_master/out/host/linux-x86/framework/core.art --dex-file=/tmp/iam/test-126444/639-checker-code-sinking-classloaders.jar --oat-file=/tmp/iam/test-126444/oat/x86/639-checker-code-sinking-classloaders.odex --base=0x4000 --app-image-file=/tmp/iam/test-126444/oat/x86/639-checker-code-sinking-classloaders.art --instruction-set=x86 --watchdog-timeout=60000 && true && true && true && timeout -k 120s -s SIGRTMIN+2 2400s /mnt/ssd3/workspace/aosp_master/out/host/linux-x86/bin/dalvikvm32 -Xcompiler-option --compiler-backend=Optimizing -XX:ThreadSuspendTimeout=500000 -Djava.library.path=/mnt/ssd3/workspace/aosp_master/out/host/linux-x86/lib:/mnt/ssd3/workspace/aosp_master/out/host/linux-x86/nativetest -Xcompiler-option --dump-cfg=/tmp/iam/test-126444/graph.cfg -Xcompiler-option -j1 -XX:SlowDebug=true -Xnorelocate -XXlib:libartd.so -Xjnigreflimit:512 -Xcheck:jni -Ximage:/mnt/ssd3/workspace/aosp_master/out/host/linux-x86/framework/core.art -XX:DumpNativeStackOnSigQuit:false -cp /tmp/iam/test-126444/639-checker-code-sinking-classloaders.jar Main arttestd
dex2oatd I 07-11 10:51:01 126561 126561 dex2oat.cc:2976] /mnt/ssd3/workspace/aosp_master/out/host/linux-x86/bin/dex2oatd --compiler-backend=Optimizing --dump-cfg=/tmp/iam/test-126444/graph.cfg -j1 --runtime-arg -Xnorelocate --boot-image=/mnt/ssd3/workspace/aosp_master/out/host/linux-x86/framework/core.art --dex-file=/tmp/iam/test-126444/639-checker-code-sinking-classloaders.jar --oat-file=/tmp/iam/test-126444/oat/x86/639-checker-code-sinking-classloaders.odex --base=0x4000 --app-image-file=/tmp/iam/test-126444/oat/x86/639-checker-code-sinking-classloaders.art --instruction-set=x86 --watchdog-timeout=60000
dex2oatd I 07-11 10:51:01 126561 126561 heap.cc:2844] Explicit concurrent copying GC freed 7(14KB) AllocSpace objects, 0(0B) LOS objects, 99% free, 1304B/1537KB, paused 18.563ms,10.261ms total 31.205ms
dex2oatd I 07-11 10:51:01 126561 126561 dex2oat.cc:2695] dex2oat took 441.086ms (354.692ms cpu) (threads: 1) arena alloc=186KB (190896B) java alloc=17KB (17688B) native alloc=449KB (460656B) free=146KB (149648B)
dex2oatd I 07-11 10:51:01 126561 126561 dex2oat.cc:2695] Code dedupe: 0 collisions, 0 max hash collisions, 0/6 probe distance, 2422 ns hash time
dex2oatd I 07-11 10:51:01 126561 126561 dex2oat.cc:2695] Vmap table dedupe: 0 collisions, 0 max hash collisions, 0/7 probe distance, 1152 ns hash time
dex2oatd I 07-11 10:51:01 126561 126561 dex2oat.cc:2695] CFI info dedupe: 0 collisions, 0 max hash collisions, 0/0 probe distance, 0 ns hash time
dex2oatd W 07-11 10:51:01 126561 126561 runtime.cc:288] Current thread not detached in Runtime shutdown
D/ICU     (126564): No timezone override file found: /tmp/iam/test-126444/misc/zoneinfo/current/icu/icu_tzdata.dat
dex2oatd I 07-11 10:51:02 126570 126570 dex2oat.cc:2976] /mnt/ssd3/workspace/aosp_master/out/host/linux-x86/bin/dex2oatd --runtime-arg -classpath --runtime-arg /tmp/iam/test-126444/639-checker-code-sinking-classloaders.jar --instruction-set=x86 --instruction-set-features=-ssse3,-sse4.1,-sse4.2,-avx,-avx2,-popcnt --runtime-arg -Xnorelocate --host --boot-image=/mnt/ssd3/workspace/aosp_master/out/host/linux-x86/framework/core.art --compiler-backend=Optimizing --dump-cfg=/tmp/iam/test-126444/graph.cfg -j1 --dex-file=/tmp/iam/test-126444/639-checker-code-sinking-classloaders-ex.jar --output-vdex-fd=8 --oat-fd=9 --oat-location=/tmp/iam/test-126444/oat/x86/639-checker-code-sinking-classloaders-ex.odex --compiler-filter=quicken
dex2oatd I 07-11 10:51:02 126570 126570 dex2oat.cc:2695] dex2oat took 171.767ms (98.522ms cpu) (threads: 1) arena alloc=2736B (2736B) java alloc=16KB (16416B) native alloc=291KB (298112B) free=76KB (78720B)
dex2oatd I 07-11 10:51:02 126570 126570 dex2oat.cc:2695] Code dedupe: 0 collisions, 0 max hash collisions, 0/0 probe distance, 0 ns hash time
dex2oatd I 07-11 10:51:02 126570 126570 dex2oat.cc:2695] Vmap table dedupe: 0 collisions, 0 max hash collisions, 0/3 probe distance, 566 ns hash time
dex2oatd I 07-11 10:51:02 126570 126570 dex2oat.cc:2695] CFI info dedupe: 0 collisions, 0 max hash collisions, 0/0 probe distance, 0 ns hash time
dex2oatd W 07-11 10:51:02 126570 126570 runtime.cc:288] Current thread not detached in Runtime shutdown
dalvikvm32 W 07-11 10:51:02 126564 126564 oat_file_manager.cc:582] Skipping duplicate class check due to unrecognized classloader
ExMain
java.lang.Object
ExOther
error: Test case not found in the CFG file
ExMain.java:19: void ExMain.doTest() code_sinking (before)
checker exit status: 1
run exit status: 0
/mnt/ssd3/workspace/aosp_master/art/test/639-checker-code-sinking-classloaders: FAILED!
 
#################### info
# Checker tests for the code sinking optimization pass to validate HLoadClass sinking.
#################### diffs
diff: output.txt: No such file or directory
####################

Patch-set: 1
Reviewer: Gerrit User 1021471 <1021471@85c56323-6fa9-3386-8a01-6480fb634889>