Update patch set 1
Patch Set 1:

> Nicolas, could you please provide me exact command you run tests.
 > 
 > I do the following:
 > 1) lunch aosp_x86-eng
 > 2) make test-art-host
 > 
 > Separately run via: ./run-test --host 458-checker-instruction-simplification
 > 
 > And tests are passed for me in both cases

just do ART_TEST_OPTIMIZING=true m -j32 test-art-host-run-test-optimizing

You'll get three failures:
test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-458-checker-instruction-simplification32
test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-458-checker-instruction-simplification64
test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-537-checker-jump-over-jump64


[ 61% 498/815] build test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-458-checker-instruction-simplification32
checker exit status: 1
/usr/local/google/home/ngeoffray/projects/android/standalone3/art/test/458-checker-instruction-simplification: FAILED!
 
#################### info
# Tests arithmetic identities optimizations in the optimizing compiler.
#################### diffs
--- expected.txt	2015-05-22 14:01:17.574368044 +0100
+++ output.txt	2016-01-29 13:03:25.448392537 +0000
@@ -0,0 +1,2 @@
+Main.java:1439: error: Missing definition of variable "LE"
+Missing definition of variable "LE"
####################
 
458-checker-instruction-simplification files deleted from host 
test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-458-checker-instruction-simplification32 FAILED
[ 61% 499/815] build test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-458-checker-instruction-simplification64
checker exit status: 1
/usr/local/google/home/ngeoffray/projects/android/standalone3/art/test/458-checker-instruction-simplification: FAILED!
 
#################### info
# Tests arithmetic identities optimizations in the optimizing compiler.
#################### diffs
--- expected.txt	2015-05-22 14:01:17.574368044 +0100
+++ output.txt	2016-01-29 13:03:27.392397888 +0000
@@ -0,0 +1,2 @@
+Main.java:1439: error: Missing definition of variable "LE"
+Missing definition of variable "LE"
####################
 
458-checker-instruction-simplification files deleted from host 
test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-458-checker-instruction-simplification64 FAILED
[ 82% 670/815] build test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-537-checker-jump-over-jump64
checker exit status: 1
/usr/local/google/home/ngeoffray/projects/android/standalone3/art/test/537-checker-jump-over-jump: FAILED!
 
#################### info
# Test for X86-64 elimination of jump over jump.
#################### diffs
--- expected.txt	2015-11-06 15:22:01.102504911 +0000
+++ output.txt	2016-01-29 13:07:09.589009257 +0000
@@ -0,0 +1,2 @@
+Main.java:27: error: Assertion could not be matched starting from line 17683
+Assertion could not be matched starting from line 17683
####################
 
537-checker-jump-over-jump files deleted from host 
test-art-host-run-test-debug-prebuild-optimizing-relocate-ntrace-cms-checkjni-image-npictest-ndebuggable-537-checker-jump-over-jump64 FAILED

Patch-set: 1