Update patch set 3
Patch Set 3:

> Patch Set 3: Code-Review-1
> 
> It seems to be failing on macOS; I'll post the error message ASAP.

Here's the error message I got with this CL cherry-picked on top of AOSP ToT:

  $ mmma -j8 art
  ============================================
  PLATFORM_VERSION_CODENAME=Q
  PLATFORM_VERSION=Q
  TARGET_PRODUCT=aosp_arm64
  TARGET_BUILD_VARIANT=eng
  TARGET_BUILD_TYPE=release
  TARGET_ARCH=arm64
  TARGET_ARCH_VARIANT=armv8-a
  TARGET_CPU_VARIANT=generic
  TARGET_2ND_ARCH=arm
  TARGET_2ND_ARCH_VARIANT=armv8-a
  TARGET_2ND_CPU_VARIANT=generic
  HOST_ARCH=x86_64
  HOST_OS=darwin
  HOST_OS_EXTRA=Darwin-17.7.0-x86_64-10.13.6
  HOST_BUILD_TYPE=release
  BUILD_ID=PI
  OUT_DIR=out
  ============================================
  out/target/product/generic_arm64/clean_steps.mk was modified, regenerating...
  [  0% 94/11186] //frameworks/base/tools/aapt2:libaapt2 clang++ io/ZipArchive.cpp [darwin]
  FAILED: out/soong/.intermediates/frameworks/base/tools/aapt2/libaapt2/darwin_x86_64_static/obj/frameworks/base/tools/aapt2/io/ZipArchive.o
   prebuilts/clang/host/darwin-x86/clang-r339409b/bin/clang++ -c -Iframeworks/base/tools/aapt2  -fPIC -funwind-tables -D__STDC_FORMAT_MACROS -D__STDC_CONSTANT_MACROS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.8 -DMACOSX_DEPLOYMENT_TARGET=10.8 -m64 -integrated-as -fstack-protector-strong -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -D__compiler_offsetof=__builtin_offsetof -Wimplicit-fallthrough -Wno-error=implicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -Wno-zero-as-null-pointer-constant -Wno-deprecated-register -Wno-sign-compare   -Iout/soong/.intermediates/frameworks/base/tools/aapt2/libaapt2/darwin_x86_64_static/gen/proto/frameworks/base/tools/aapt2 -Iout/soong/.intermediates/frameworks/base/tools/aapt2/libaapt2/darwin_x86_64_static/gen/proto -Iframeworks/base/libs/androidfw/include -Iexternal/zlib -Isystem/core/libutils/include -Isystem/core/liblog/include -Isystem/core/libsystem/include -Isystem/core/libcutils/include -Iexternal/expat/lib -Isystem/core/libziparchive/include -Iexternal/libpng -Isystem/core/base/include -Iexternal/protobuf/src -Iexternal/libcxx/include -Iexternal/libcxxabi/include -Isystem/core/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Ilibnativehelper/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include  -Ilibnativehelper/include_jni -Wall -Werror -Wno-unused-parameter -D_DARWIN_UNLIMITED_STREAMS -target x86_64-apple-darwin -B/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -DANDROID_STRICT -DGOOGLE_PROTOBUF_NO_RTTI -fPIC -D_USING_LIBCXX -std=gnu++14 -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -Wno-thread-safety-negative -Wno-gnu-include-next  -Wno-missing-field-initializers -fno-exceptions -fno-rtti  -D_LIBCPP_DISABLE_AVAILABILITY -nostdinc++ -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-null-pointer-arithmetic -Wno-enum-compare -Wno-enum-compare-switch -Wno-c++98-compat-extra-semi -Wno-self-assign-overloaded -Wno-constant-logical-operand -Wno-return-std-move-in-c++11 -Wno-dangling-field -MD -MF out/soong/.intermediates/frameworks/base/tools/aapt2/libaapt2/darwin_x86_64_static/obj/frameworks/base/tools/aapt2/io/ZipArchive.o.d -o out/soong/.intermediates/frameworks/base/tools/aapt2/libaapt2/darwin_x86_64_static/obj/frameworks/base/tools/aapt2/io/ZipArchive.o frameworks/base/tools/aapt2/io/ZipArchive.cpp
  In file included from frameworks/base/tools/aapt2/io/ZipArchive.cpp:17:
  In file included from frameworks/base/tools/aapt2/io/ZipArchive.h:20:
  system/core/libziparchive/include/ziparchive/zip_archive.h:102:3: error: unknown type name 'off64_t'; did you mean 'off_t'?
    off64_t offset;
    ^~~~~~~
    off_t
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/_types/_off_t.h:31:25: note: 'off_t' declared here
  typedef __darwin_off_t          off_t;
                                  ^
  1 error generated.
  18:33:21 ninja failed with: exit status 1

Patch-set: 3
Reviewer: Gerrit User 1052644 <1052644@85c56323-6fa9-3386-8a01-6480fb634889>