Calling @IntraCoreApi from core-icu4j should not cause "Core platform API violation"
Treat I18n APEX as the same domain as ART and Conscrypt APEX.

Remove unused varaiable isJavaDebuggable because it causes the
NoSuchMethodError for unkown reason.
java.lang.NoSuchMethodError: No virtual method isJavaDebuggable()Z in class Ldalvik/system/VMRuntime; or its super classes (declaration of 'dalvik.system.VMRuntime' appears in /apex/com.android.art/javalib/core-libart.jar)

Bug: 138994281
Test: art/test/run-test --chroot $ART_TEST_CHROOT 674-hiddenapi
Change-Id: Icb7e98b5cd7143c06c05dd4377af0c96ba75bca7